// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/qmk/qmk_firmware/keyboards/nessie/drawing/logo.gif --output /home/qmk/qmk_firmware/keyboards/nessie/drawing --format mono16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_logo_length;
extern const uint8_t  gfx_logo[9641];
