
QUANTUM_PAINTER_DRIVERS += ili9341_spi
QUANTUM_PAINTER_DRIVERS += surface

QUANTUM_PAINTER_LVGL_INTEGRATION = yes

POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
SPI_DRIVER_REQUIRED = yes

TRI_LAYER_ENABLE = yes
SEND_STRING_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

POINTING_DEVICE_DEBUG = yes



SRC += display.c
